exceptionList = {"First-person shooter",
"Category:First-person shooters",
"Doom (1993 video game)",
"Counter-Strike (video game)",
"Wolfenstein 3D",
"Call of Duty",
"Quake (video game)",
"Battlefield (video game series)",
"First-person shooter engine",
"007 Legends",
"007: Quantum of Solace",
"3D Monster Chase",
"Ace of Spades (video game)",
"Alcatraz: Prison Escape",
"Alien Arena (video game)",
"Alien Breed 3D",
"Alien Breed 3D II: The Killing Grounds",
"Alien Rage",
"Alien: Resurrection (video game)",
"Aliens: Colonial Marines",
"Alien vs Predator (Atari Jaguar game)",
"List of Alien, Predator, and Alien vs. Predator games",
"Aliens versus Predator 2",
"Aliens vs. Predator (2010 video game)",
"Alien Trilogy",
"Alliance of Valiant Arms",
"Alpha Prime",
"Black Mesa (video game)",
"America%27s Army",
"Area 51 (2005 video game)",
"ARMA: Armed Assault",
"ARMA 2",
"ARMA 2: Operation Arrowhead",
"Operation Flashpoint: Cold War Crisis",
"ARMA 3",
"Armorines: Project S.W.A.R.M.",
"List of first-person shooters",
"Arx Fatalis",
"Ashes to Ashes (video game)",
"Assassin 2015",
"Back Track",
"Bad Toys 3D",
"Ballistic: Ecks vs. Sever (video game)",
"Battlefield 1942",
"Battlefield 1943",
"Battlefield 1",
"Battlefield 2",
"Battlefield 3",
"Battlefield 4",
"Battlefield V",
"Battlefield Hardline",
"Battlefield 2142",
"Battlefield: Bad Company",
"Battlefield: Bad Company 2",
"Battlefield Heroes",
"Battlefield Vietnam",
"Battlezone (1980 video game)",
"Bloodshot (video game)",
"Battlestrike",
"Bet On Soldier: Blood Sport",
"BioShock",
"BioShock 2",
"BioShock Infinite",
"Black (video game)",
"Blacklight: Retribution",
"Blacklight: Tango Down",
"List of first-person shooters",
"BlackSite: Area 51",
"Blake Stone: Aliens of Gold",
"Blake Stone: Planet Strike",
"Blood (video game)",
"Blood (video game)#Plasma Pak",
"Blood II: The Chosen",
"Blood II: The Chosen#The Nightmare Levels",
"Bloodline (video game)",
"Boiling Point: Road to Hell",
"Borderlands (video game)",
"Borderlands 2",
"Borderlands: The Pre-Sequel",
"Bram Stoker%27s Dracula (video game)",
"Breathless (video game)",
"Breed (video game)",
"Brink (video game)",
"Brothers in Arms: Road to Hill 30",
"Brothers in Arms: Earned in Blood",
"Brothers in Arms: Hell%27s Highway",
"Breach (video game)",
"Bulletstorm",
"Call of Cthulhu: Dark Corners of the Earth",
"Call of Duty (video game)",
"Call of Duty: Finest Hour",
"Call of Duty: United Offensive",
"Call of Duty 2",
"Call of Duty 2: Big Red One",
"Call of Duty 3",
"Call of Duty 4: Modern Warfare",
"Call of Duty: Modern Warfare 2",
"Call of Duty: Modern Warfare 3",
"Call of Duty: Ghosts",
"Call of Duty: Advanced Warfare",
"Call of Duty: Infinite Warfare",
"Call of Duty: World at War",
"Call of Duty: Black Ops",
"Call of Duty: Black Ops II",
"Call of Duty: Black Ops III",
"Call of Duty: WWII",
"Call of Duty: Black Ops 4",
"Call of Juarez",
"Call of Juarez: Bound in Blood",
"Call of Juarez: Gunslinger",
"Call of Juarez: The Cartel",
"Carnivores (video game)",
"Carnivores 2",
"Chaser (video game)",
"Chasm: The Rift",
"Castaway: The Ordeal Begins",
"Castle Master",
"Catacomb 3-D",
"Catacomb 3-D#Catacomb Abyss",
"Catacomb 3-D#Catacomb Armageddon",
"Catacomb 3-D",
"Catechumen (video game)",
"Chex Quest",
"Chex Quest#Chex Quest 2: Flemoids Take Chextropolis",
"Chex Quest#Chex Quest 3",
"Chicken Blaster",
"Christmas Carnage",
"Chrome (video game)",
"Chrome (video game)",
"The Chronicles of Riddick: Escape from Butcher Bay",
"The Chronicles of Riddick: Assault on Dark Athena",
"CIA Operative: Solo Missions",
"Citadel (1995 video game)",
"Clive Barker%27s Jericho",
"Clive Barker%27s Undying",
"Close Combat: First to Fight",
"Codename Eagle",
"Codename MAT",
"Codename: Nina - Global Terrorism Strike Force",
"Codename: Outbreak",
"The Colony (video game)",
"Combat Arms (video game)",
"Command %26 Conquer: Renegade",
"Commandos: Strike Force",
"The Conduit",
"Conduit 2",
"Congo The Movie: The Lost City of Zinj",
"Contract J.A.C.K.",
"Corporation (video game)",
"Corridor 7: Alien Invasion",
"Cosmic Conflict",
"Counter-Strike",
"Counter-Strike: Condition Zero",
"Counter-Strike: Source",
"Counter-Strike: Global Offensive",
"List of first-person shooters",
"CrossFire (video game)",
"CTU: Marine Sharpshooter",
"Cryostasis: Sleep of Reason",
"Blood (video game)#Cryptic Passage",
"Crysis",
"Crysis Warhead",
"Crysis 2",
"Crysis 3",
"The Assembly Line",
"Cyberdillo",
"CyberMage: Darklight Awakening",
"CyClones",
"Midas Interactive Entertainment",
"Daikatana",
"Damage Incorporated",
"Dark Arena",
"Dark Side (video game)",
"The Darkness (video game)",
"The Darkness II",
"Day of Defeat",
"Day of Defeat: Source",
"Day of the Viper",
"Dead Island",
"Dead Island: Riptide",
"Deadly Dozen",
"Human Head Studios",
"Defcon 5 (video game)",
"Delta Force (video game)",
"Delta Force 2",
"Delta Force: Land Warrior",
"Delta Force: Task Force Dagger",
"Delta Force: Urban Warfare",
"Delta Force: Black Hawk Down",
"Delta Force: Xtreme",
"Delta Force: Xtreme 2",
"Dementium: The Ward",
"Depth Dwellers",
"Descent (1995 video game)",
"Descent II",
"Destiny (video game)",
"Destiny 2",
"Deus Ex: Human Revolution",
"Deus Ex: Mankind Divided",
"Pac-Man %26 Galaga Dimensions",
"Pie in the Sky (game engine)#Despair series",
"Deus (video game)",
"Devastation (video game)",
"Die Hard: Nakatomi Plaza",
"Dishonored",
"Disruptor (video game)",
"Doom (1993 video game)",
"Doom II",
"Doom 3",
"Doom 3: Resurrection of Evil",
"Doom 3: BFG Edition",
"Doom 64",
"Doom (2016 video game)",
"Dreamkiller",
"Driller (video game)",
"Duke Nukem 3D",
"Duke Nukem 3D#PC versions",
"Duke Nukem 3D#Expansion packs",
"Duke Nukem 3D#Expansion packs",
"Duke Nukem 3D#Expansion packs",
"Duke Nukem Forever",
"Dusk (video game)",
"Ecks vs. Sever",
"Enemy Territory: Quake Wars",
"Epidemic (video game)",
"Eradicator (video game)",
"Escape from Monster Manor",
"Extreme Paintbrawl",
"Extreme Paintbrawl#Sequels",
"Extreme Paintbrawl#Sequels",
"F.E.A.R.",
"F.E.A.R. 2: Project Origin",
"F.E.A.R. 3",
"Far Cry",
"Far Cry 2",
"Far Cry 3",
"Far Cry 4",
"Far Cry 5",
"Far Cry 3: Blood Dragon",
"Far Cry Instincts",
"Far Cry Vengeance",
"Far Cry Primal",
"Final Doom",
"Flying Heroes",
"Forbes Corporate Warrior",
"The Fortress of Dr. Radiaki",
"Frontlines: Fuel of War",
"Mojang#games",
"Geist (video game)",
"Ghost in the Shell: Stand Alone Complex (2005 video game)",
"Ghost Squad (video game)",
"Ghost Squad (video game)#Ghost Squad: Evolution (Arcade)",
"Global Operations",
"Gloom (video game)",
"Gods and Generals (video game)",
"GoldenEye 007 (1997 video game)",
"GoldenEye 007 (2010 video game)",
"GoldenEye: Rogue Agent",
"Golgo 13: Top Secret Episode",
"Gore: Ultimate Soldier",
"Gun Buster (arcade game)",
"Gunman Chronicles",
"Gunmetal (video game)",
"H.U.R.L.",
"Doom WAD#Total conversions",
"Hades 2",
"Half-Life 2: Episode One",
"Half-Life 2: Episode Two",
"Half-Life (video game)",
"Half-Life 2",
"Half-Life: Blue Shift",
"Half-Life: Decay",
"Half-Life: Opposing Force",
"Halo: Combat Evolved",
"Halo: Combat Evolved Anniversary",
"Halo 2",
"Halo 3",
"Halo 3: ODST",
"Halo: Reach",
"Halo 4",
"Halo 5: Guardians",
"Hard Reset",
"Haze (video game)",
"Heat Project",
"Heavy Fire",
"Heavy Fire",
"Heavy Fire",
"Heavy Fire",
"Heretic (video game)",
"Heretic (video game)",
"Hexen: Beyond Heretic",
"Hexen: Beyond Heretic",
"Hexen II",
"Hexen II#Portal of Praevus",
"Hidden %26 Dangerous",
"Hidden %26 Dangerous 2",
"Homefront (video game)",
"Homefront: The Revolution",
"Hovertank 3D",
"Nasir Gebelli#Gebelli Software",
"I.G.I.-2: Covert Strike",
"In Pursuit of Greed",
"Interphase (video game)",
"Iron Angel of the Apocalypse",
"Iron Angel of the Apocalypse: The Return",
"Iron Storm (2002 video game)",
"Island Peril",
"Isle of the Dead (video game)",
"James Bond 007: Agent Under Fire",
"James Bond 007: Nightfire",
"Joint Operations: Typhoon Rising",
"Joint Operations: Typhoon Rising",
"Judge Dredd: Dredd vs. Death",
"Quake II#Mods",
"Jumping Flash!",
"Jumping Flash! 2",
"Trespasser (video game)",
"Ken%27s Labyrinth",
"Mobile Suit Z Gundam: Hot Scramble",
"Kileak: The DNA Imperative",
"Killing Time (video game)",
"Killzone (series)",
"Killzone 2",
"Killzone 3",
"Killzone: Mercenary",
"Killzone Shadow Fall",
"Kingpin: Life of Crime",
"Peter Jackson%27s King Kong",
"Kiss: Psycho Circus: The Nightmare Child",
"Land of the Dead: Road to Fiddler%27s Green",
"Laser Arena",
"Left 4 Dead",
"Left 4 Dead 2",
"Legendary (video game)",
"Build (game engine)",
"Legends of Might and Magic",
"Pie in the Sky (game engine)#Lethal Tender",
"Lifeforce Tenka",
"Line of Sight: Vietnam",
"Lunicus",
"Mace Griffin: Bounty Hunter",
"MAG (video game)",
"Malice (1997 video game)",
"Marathon (video game)",
"Marathon 2: Durandal",
"Marathon Infinity",
"CTU: Marine Sharpshooter#Marine Sharpshooter II: Jungle Warfare",
"Doom II#Master Levels for Doom II",
"Maze War",
"Medal of Honor (1999 video game)",
"Medal of Honor: Underground",
"Medal of Honor: Allied Assault",
"Medal of Honor: Frontline",
"Medal of Honor: Rising Sun",
"Medal of Honor: Pacific Assault",
"Medal of Honor: European Assault",
"Medal of Honor: Heroes",
"Medal of Honor: Vanguard",
"Medal of Honor: Airborne",
"Medal of Honor: Heroes 2",
"Medal of Honor (2010 video game)",
"Medal of Honor: Warfighter",
"Men of Valor",
"Metal Head",
"Metro 2033 (video game)",
"Metro: Last Light",
"Metroid Prime",
"Metroid Prime 2: Echoes",
"Metroid Prime 3: Corruption",
"MIDI Maze",
"Midwinter (video game)",
"Mission Against Terror",
"Mob Enforcer",
"Mobile Forces",
"Mortal Coil: Adrenalin Intelligence",
"Mortyr",
"NAM (video game)",
"Natural Selection (video game)",
"NecroVisioN",
"NecroVisioN#Prequel",
"Nerf Arena Blast",
"Neuro Hunter",
"Neuro (video game)",
"New World Order (video game)",
"Nitemare 3D",
"No One Lives Forever 2: A Spy in H.A.R.M.%27s Way",
"Nosferatu: The Wrath of Malachi",
"NRA Gun Club",
"Oddworld: Stranger%27s Wrath",
"Ominous Horizons: A Paladin%27s Calling",
"Onslaught (2009 video game)",
"Operation: Blockade",
"Operation Body Count",
"Operation Flashpoint: Cold War Crisis",
"Operation Flashpoint: Dragon Rising",
"Operation Flashpoint: Red River",
"Operation: Matriarchy",
"The Operative: No One Lives Forever",
"Outcast (video game)",
"Outlaws (1997 video game)",
"Outtrigger",
"Overwatch (video game)",
"Painkiller (video game)",
"Painkiller (video game)#Painkiller: Battle Out of Hell",
"Painkiller: Hell %26 Damnation",
"Painkiller: Overdose",
"Painkiller (video game)#Painkiller: Recurring Evil",
"Painkiller (video game)#Painkiller: Redemption",
"Painkiller: Resurrection",
"Paladins (video game)",
"Pariah (video game)",
"Parkan (series)",
"Parkan (series)",
"Parkan (series)",
"Pathways into Darkness",
"Patriots: A Nation Under Fire",
"Pie in the Sky (game engine)#Pencil Whipped",
"Perfect Dark",
"Perfect Dark Zero",
"Perfect Dark (2010 video game)",
"Phantom Slayer (video game)",
"PlanetSide",
"PlanetSide 2",
"PO%27ed",
"Point Blank (2008 video game)",
"Portal (video game)",
"Portal 2",
"Postal 2",
"PowerSlave",
"Precursors (video game)",
"Prey (2006 video game)",
"Prey Invasion",
"Prey (2017 video game)",
"Prime Target",
"Project Eden (video game)",
"Project I.G.I.: I%27m Going In",
"Project Snowblind",
"Quake (video game)",
"Quake (video game)#Quake Mission Pack No. 1: Scourge of Armagon",
"Quake (video game)#Quake Mission Pack No. 2: Dissolution of Eternity",
"Quake II",
"Quake II#Quake II Mission Pack: Ground Zero",
"Quake II#Quake II Mission Pack: The Reckoning",
"Quake III Arena",
"Quake III Arena#Expansion",
"Quake 4",
"Quake Live",
"Quest for Bush",
"Quest for Saddam",
"Quest of Persia",
"Quiver (video game)",
"Radix: Beyond the Void",
"Rage (video game)",
"Raven Squad: Operation Hidden Dagger",
"Realms of the Haunting",
"Rebel Moon Rising",
"Rec Room (video game)",
"Pie in the Sky (game engine)#Red Babe",
"Red Faction",
"Red Faction II",
"Redneck Rampage",
"Redneck Rampage",
"Redneck Rampage",
"Red Ocean",
"Red Orchestra: Ostfront 41-45",
"Red Orchestra 2: Heroes of Stalingrad",
"Red Steel",
"Red Steel 2",
"Redline (1999 video game)",
"The Regiment (video game)",
"Renegade X",
"Requiem: Avenging Angel",
"Rescue on Fractalus!",
"Resident Evil 7: Biohazard",
"Resident Evil: The Darkside Chronicles",
"Resident Evil: The Umbrella Chronicles",
"Resident Evil: Dead Aim",
"Resident Evil Survivor",
"Resident Evil Survivor 2 %E2%80%93 Code: Veronica",
"Resistance: Fall of Man",
"Resistance 2",
"Resistance 3",
"Resistance: Burning Skies",
"Return to Castle Wolfenstein",
"Rise of the Triad",
"Rise of the Triad (2013 video game)",
"Rising Storm (video game)",
"Rising Storm 2: Vietnam",
"RoboCop (2003 video game)",
"RoboCop 3 (video game)",
"Robotica (video game)",
"Rogue Warrior (video game)",
"Saucer Attack",
"SAS: Secure Tomorrow",
"Savage: The Battle for Newerth",
"Savage 2: A Tortured Soul",
"Scarab of Ra",
"Scorpion: Disfigured",
"Secret Service (2008 video game)",
"Secret Service (2001 video game)",
"Secret Service 2",
"Section 8 (video game)",
"Section 8: Prejudice",
"Serious Sam 3: BFE",
"Serious Sam (video game)#Serious Sam: The First Encounter",
"Serious Sam (video game)#Serious Sam: The Second Encounter",
"Serious Sam 2",
"Shadow Ops: Red Mercury",
"Shadowrun (2007 video game)",
"Shadow Warrior",
"Shadow Warrior (2013 video game)",
"Shadow Warrior 2",
"Shattered Horizon",
"Shellshock 2: Blood Trails",
"The Ship (video game)",
"Shogo: Mobile Armor Division",
"Quake (video game)#Mods and add-ons",
"Silent Debuggers",
"SiN",
"SiN Episodes",
"Singularity (video game)",
"Smokin%27 Guns",
"Sniper: Ghost Warrior",
"Sniper: Ghost Warrior 2",
"Sniper: Ghost Warrior 3",
"Solarix",
"Soldier of Fortune (video game)",
"Soldier of Fortune II: Double Helix",
"Soldier of Fortune: Payback",
"Soulcrusher (Operator album)",
"South Park (video game)",
"Space Hulk (1993 video game)",
"Space Hulk: Vengeance of the Blood Angels",
"Spasim",
"Wolfenstein 3D",
"Special Force (2003 video game)",
"Special Force 2: Tale of the Truthful Pledge",
"Special Operation 85: Hostage Rescue",
"Spec Ops: Rangers Lead the Way",
"Spec Ops: Rangers Lead the Way#Expansion",
"Spec Ops II: Green Berets",
"Spec Ops II: Green Berets",
"Splat Magazine Renegade Paintball",
"The Stalin Subway",
"S.T.A.L.K.E.R.: Shadow of Chernobyl",
"S.T.A.L.K.E.R.: Clear Sky",
"S.T.A.L.K.E.R.: Call of Pripyat",
"Star Cruiser",
"Star Cruiser",
"Star Luster",
"Star Raiders",
"Star Raiders II",
"Star Ship",
"Starhawk (1979 video game)",
"Starship Troopers (video game)",
"Starfox",
"Starsiege: Tribes",
"Star Trek (arcade game)",
"Star Trek: Voyager %E2%80%93 Elite Force",
"Star Trek: Elite Force II",
"Star Trek: The Next Generation: Klingon Honor Guard",
"Star Wars: Battlefront (2004 video game)",
"Star Wars: Battlefront II (2005 video game)",
"Star Wars: Dark Forces",
"Star Wars Jedi Knight: Dark Forces II",
"Star Wars Jedi Knight: Mysteries of the Sith",
"Star Wars Jedi Knight II: Jedi Outcast",
"Star Wars Jedi Knight: Jedi Academy",
"Star Wars: Republic Commando",
"Stellar 7",
"Strafe (video game)",
"Strife (1996 video game)",
"Submarine Commander",
"Super 3D Noah%27s Ark",
"SWAT 3: Close Quarters Battle",
"SWAT: Global Strike Team",
"SWAT 4",
"System Shock",
"System Shock 2",
"Tactical Ops: Assault on Terror",
"Tau Ceti (video game)",
"Team Fortress Classic#Development",
"Team Fortress 2",
"Team Fortress Classic",
"Pie in the Sky (game engine)#Terminal Terror",
"List of Terminator video games#The Terminator (DOS)",
"The Terminator: Rampage",
"The Terminator: Future Shock",
"Skynet (video game)",
"Terminator 3: Rise of the Machines (video game)",
"Terminator 3: War of the Machines",
"Terra Nova: Strike Force Centauri",
"Terrawars: New York Invasion",
"Shivam Sai Gupta",
"Pie in the Sky (game engine)#Terror in Christmas Town",
"Testament (video game)",
"Titanfall",
"Titanfall 2",
"Official versions of Doom#The Ultimate Doom",
"The Walking Dead: Survival Instinct",
"Time Crisis 4",
"TimeShift",
"TimeSplitters",
"TimeSplitters 2",
"TimeSplitters: Future Perfect",
"Tom Clancy%27s Ghost Recon (2001 video game)",
"Tom Clancy%27s Ghost Recon Advanced Warfighter",
"Tom Clancy%27s Ghost Recon Advanced Warfighter 2",
"Tom Clancy%27s Rainbow Six (video game)",
"Tom Clancy%27s Rainbow Six: Rogue Spear",
"Tom Clancy%27s Rainbow Six: Take-Down %E2%80%93 Missions in Korea",
"Tom Clancy%27s Rainbow Six 3: Raven Shield",
"Tom Clancy%27s Rainbow Six: Lockdown",
"Tom Clancy%27s Rainbow Six: Vegas",
"Tom Clancy%27s Rainbow Six: Vegas 2",
"Total Eclipse (1988 video game)",
"Tower of Guns",
"Tribes 2",
"Tribes Aerial Assault",
"Tribes: Vengeance",
"Tron 2.0",
"The Truth About 9th Company",
"Tunnel Rats: 1968",
"Turning Point: Fall of Liberty",
"Turok: Dinosaur Hunter",
"Turok 2: Seeds of Evil",
"Turok: Rage Wars",
"Turok 3: Shadow of Oblivion",
"Turok: Evolution",
"Turok (video game)",
"Twin Sector",
"%C3%9CberSoldier",
"Cmune#UberStrike",
"Under Ash",
"Under Siege (2005 video game)",
"Unreal (1998 video game)",
"Unreal (1998 video game)",
"Unreal II: The Awakening",
"Unreal Tournament",
"Unreal Tournament 2003",
"Unreal Tournament 2004",
"Unreal Tournament 3",
"Urban Chaos: Riot Response",
"Urban Terror",
"U.S. Special Forces: Team Factor",
"Vietcong (video game)",
"Vietcong 2",
"Vivisector: Beast Within",
"Warface",
"Warhammer 40,000: Fire Warrior",
"Warpath (video game)",
"Water Warfare (video game)",
"The Wheel of Time (video game)",
"White Gold: War in Paradise",
"Ethnic Cleansing (video game)#Sequel",
"William Shatner%27s TekWar",
"Will Rock",
"Witchaven",
"Witchaven II: Blood Vengeance",
"Wolfenstein: The New Order",
"Wolfenstein: The Old Blood",
"Wolfenstein II: The New Colossus",
"Wolfenstein (2009 video game)",
"Wolfenstein 3D",
"Wolfenstein: Enemy Territory",
"The World Is Not Enough (Nintendo 64)",
"The World Is Not Enough (PlayStation)",
"World War II Combat: Iwo Jima",
"World War II Combat: Road to Berlin",
"World War II GI",
"X-Men: The Ravages of Apocalypse",
"Xenomorph (video game)",
"XIII (video game)",
"Xonotic",
"XS (video game)",
"You Are Empty",
"South African Republic",
"Quake II#Mods",
"Gebelli Software",
"Zeno Clash",
"Zeno Clash II",
"Zero Tolerance (video game)",
"ZombiU",
"ADHD rating scale",
"Abnormal psychology",
"Abreaction",
"Accelerated experiential dynamic psychotherapy",
"Acceptance and commitment therapy",
"Acute stress disorder",
"Acute stress reaction",
"Addiction psychiatry",
"Adjustment disorder",
"Adventure therapy",
"Agoraphobia",
"Aichmophobia",
"Alcohol abuse",
"Alcohol dependence",
"Alcohol withdrawal",
"Alcoholic hallucinosis",
"Alcoholism",
"Alzheimer%27s disease",
"Amafufunyana",
"American Academy of Child and Adolescent Psychiatry",
"American Board of Psychiatry and Neurology",
"American Neuropsychiatric Association",
"American Psychiatric Association",
"Amnesia",
"Amphetamine dependence",
"Analytical psychology",
"Angelman syndrome",
"Animal-assisted therapy",
"Anorexia nervosa",
"Anorgasmia",
"Anosognosia",
"Antenatal depression",
"Anterograde amnesia",
"Anti-psychiatry",
"Anti-social behaviour",
"Antisocial personality disorder",
"Anxiety disorder",
"Anxiolytic",
"Applied behavior analysis",
"Applied psychology",
"Art therapy",
"Asperger syndrome",
"Atelophobia",
"Athens insomnia scale",
"Attachment-based psychotherapy",
"Attachment-based therapy (children)",
"Attachment therapy",
"Attack therapy",
"Attention deficit disorder",
"Attention deficit hyperactivity disorder",
"Atypical depression",
"Autism",
"Autism spectrum",
"Autogenic training",
"Autophagia",
"Aversion therapy",
"Avoidant/restrictive food intake disorder",
"Avoidant personality disorder",
"Barbiturate dependence",
"Basic science (psychology)",
"Behavior modification",
"Behavioral activation",
"Behavioral addiction",
"Behavioral medicine",
"Behavioral neuroscience",
"Behaviour therapy",
"Behavioural genetics",
"Benzodiazepine dependence",
"Benzodiazepine misuse",
"Benzodiazepine withdrawal",
"Bibliomania",
"Bibliotherapy",
"Binge eating disorder",
"Bioenergetic analysis",
"Biofeedback",
"Biological psychiatry",
"Bipolar II disorder",
"Bipolar I disorder",
"Bipolar disorder",
"Body dysmorphic disorder",
"Body integrity dysphoria",
"Body psychotherapy",
"Borderline intellectual functioning",
"Borderline personality disorder",
"Brief psychotherapy",
"Brief psychotic disorder",
"Brief reactive psychosis",
"Bulimia nervosa",
"Caffeine-induced anxiety disorder",
"Caffeine-induced sleep disorder",
"Cambridge Somerville Youth Study",
"Campaign Against Psychiatric Abuse",
"Cannabis dependence",
"Catatonia",
"Cerebral palsy",
"Chess therapy",
"Child and adolescent psychiatry",
"Child psychotherapy",
"Childhood disintegrative disorder",
"Chinese Society of Psychiatry",
"Circadian rhythm sleep disorder",
"Classical Adlerian psychotherapy",
"Claustrophobia",
"Clinical Depression",
"Clinical formulation",
"Clinical neuroscience",
"Clinical psychology",
"Closed-head injury",
"Clouding of consciousness",
"Cluttering",
"Co-counselling",
"Cocaine dependence",
"Cocaine intoxication",
"Cognitive analytic therapy",
"Cognitive behavior therapy",
"Cognitive disorder",
"Cognitive neuropsychiatry",
"Cognitive psychology",
"Cognitive therapy",
"Cognitivism (psychology)",
"Coherence therapy",
"Collaborative therapy",
"Communication disorder",
"Community psychology",
"Comparative psychology",
"Compassion focused therapy",
"Compulsive behavior",
"Concentrative movement therapy",
"Concussion",
"Conduct disorder",
"Consumer behaviour",
"Contemplative psychotherapy",
"Contextual therapy",
"Conversational model",
"Conversion disorder",
"Conversion therapy",
"Cotard delusion",
"Counseling",
"Counseling psychology",
"Creutzfeldt%E2%80%93Jakob disease",
"Critical psychology",
"Cross-cultural psychiatry",
"Cross-cultural psychology",
"Cultural psychology",
"Cyclothymia",
"Da Costa%27s syndrome",
"Dance movement therapy",
"Dance therapy",
"Daseinsanalysis",
"Delayed ejaculation",
"Delirium",
"Delirium tremens",
"Delusional disorder",
"Delusional parasitosis",
"Dementia",
"Dementia with Lewy bodies",
"Democratic Psychiatry",
"Dependent personality disorder",
"Depersonalization disorder",
"Depression (mood)",
"Depressive personality disorder",
"Depth psychology",
"Derealization",
"Dermatillomania",
"Dermatophagia",
"Descriptive psychiatry",
"Desynchronosis",
"Developmental Needs Meeting Strategy",
"Developmental coordination disorder",
"Developmental disability",
"Developmental disorder",
"Developmental psychology",
"Developmental regression",
"Diagnosis of schizophrenia",
"Diagnostic and Statistical Manual of Mental Disorders",
"Diagnostic overshadowing",
"Dialectical behavior therapy",
"Differential psychology",
"Diogenes Syndrome",
"Disinhibited attachment disorder",
"Disinhibited social engagement disorder",
"Disorganized schizophrenia",
"Dispareunia",
"Disruptive Behavior Disorders Rating Scale",
"Disruptive mood dysregulation disorder",
"Dissociative disorder",
"Dissociative identity disorder",
"Drama therapy",
"Dreamwork",
"Drug overdose",
"Drug withdrawal",
"Dual-role transvestism",
"Dyadic developmental psychotherapy",
"Dyscalculia",
"Dyslexia",
"Dysthymia",
"Eating disorder not otherwise specified",
"Eating disorders",
"Eating disorders and development",
"Eating mucus",
"Eclectic psychotherapy",
"Ecological counseling",
"Educational psychology",
"Effects of genocide on youth",
"Ego-dystonic sexual orientation",
"Emergency psychiatry",
"Emotional Freedom Techniques",
"Emotional and behavioral disorders",
"Emotionally focused therapy",
"Encopresis",
"Endogenous depression",
"Enemy complex",
"Enuresis",
"Environmental psychology",
"Epilepsy",
"Epworth Sleepiness Scale",
"Erectile dysfunction",
"Erotomania",
"European Psychiatric Association",
"Evolutionary psychology",
"Excoriation disorder",
"Exhibitionism",
"Existential therapy",
"Experimental psychology",
"Exposure and response prevention",
"Expressive therapies",
"Eye movement desensitization and reprocessing",
"Factitious disorder",
"Factitious disorder imposed on another",
"Factitious disorder imposed on self",
"Family Constellations",
"Family therapy",
"Female sexual arousal disorder",
"Feminist therapy",
"Focusing (psychotherapy)",
"Folie %C3%A0 deux",
"Forensic psychiatry",
"Forensic psychology",
"Fregoli delusion",
"Frontal Assessment Battery",
"Frontotemporal dementia",
"Fugue state",
"Functional analytic psychotherapy",
"Future-oriented therapy",
"Gaming disorder",
"Ganser syndrome",
"Gender dysphoria",
"General adaptation syndrome",
"Generalized anxiety disorder",
"Gerda Boyesen",
"Geriatric psychiatry",
"Gestalt theoretical psychotherapy",
"Gestalt therapy",
"Global Initiative on Psychiatry",
"Globus pharyngis",
"Grandiose delusions",
"Grief",
"Grief counseling",
"Group analysis",
"Group psychotherapy",
"Guided imagery",
"HIV-associated neurocognitive disorder",
"Hakomi",
"Hallucinogen",
"Hallucinogen persisting perception disorder",
"Health psychology",
"High-functioning autism",
"History of psychology",
"Histrionic personality disorder",
"Holotropic Breathwork",
"Hong Kong College of Psychiatrists",
"Human Givens",
"Human factors and ergonomics",
"Humanistic psychology",
"Huntington%27s disease",
"Hypercalculia",
"Hyperkinetic disorder",
"Hyperreligiosity",
"Hypersexuality",
"Hypersomnia",
"Hypnotherapy",
"Hypnotic",
"Hypoactive sexual desire disorder",
"Hypochondriasis",
"Hypokalemic sensory overstimulation",
"Hypomania",
"Hypomanic episode",
"Hysteria",
"ICD-10 Chapter V: Mental and behavioural disorders",
"Identity disorder",
"Idiopathic hypersomnia",
"Imaging genetics",
"Immuno-psychiatry",
"Impulse control disorder",
"Independent Psychiatric Association of Russia",
"Indian Psychiatric Society",
"Industrial and organizational psychology",
"Ingestive behaviors",
"Inner Relationship Focusing",
"Insomnia",
"Integral psychotherapy",
"Integrative body psychotherapy",
"Integrative milieu model",
"Integrative psychotherapy",
"Intellectual disability",
"Intensive short-term dynamic psychotherapy",
"Intermittent explosive disorder",
"Internal Family Systems Model",
"Internet phobia",
"Interpersonal psychoanalysis",
"Interpersonal psychotherapy",
"Journal therapy",
"Kleptomania",
"Korsakoff%27s syndrome",
"Labeling theory",
"Lacunar amnesia",
"Late talker",
"Legal psychology",
"Liaison psychiatry",
"Logic-based therapy",
"Logotherapy",
"Major depressive disorder",
"Major depressive episode",
"Male erectile disorder",
"Malingering",
"Mania",
"Manic episode",
"Mass psychogenic illness",
"Mathematical psychology",
"Mathematics disorder",
"Medical psychology",
"Melancholia",
"Melancholic depression",
"Mental disorder",
"Mental health",
"Mental health professional",
"Mentalization-based treatment",
"Metacognitive therapy",
"Method of levels",
"Mild cognitive impairment",
"Military acute concussion evaluation",
"Military psychiatry",
"Military psychology",
"Mindfulness-based cognitive therapy",
"Mindfulness-based stress reduction",
"Minor depressive disorder",
"Misophonia",
"Mixed episode",
"Mode deactivation therapy",
"Mood disorder",
"Morita therapy",
"Motivational interviewing",
"Motor planning",
"Multimodal therapy",
"Multisystemic therapy",
"Multitheoretical psychotherapy",
"Munchausen%27s syndrome",
"Music psychology",
"Music therapy",
"Nail biting",
"Narcissistic personality disorder",
"Narcolepsy",
"Narrative therapy",
"National Institute of Mental Health",
"Neurasthenia",
"Neurocysticercosis",
"Neurodevelopmental disorder",
"Neuroimaging",
"Neurological disorder",
"Neurophysiology",
"Neuropsychiatry",
"Neuropsychology",
"Nicotine withdrawal",
"Night eating syndrome",
"Night terror",
"Nightmare",
"Nightmare disorder",
"Nonverbal learning disorder",
"Nonviolent Communication",
"Nosophobia",
"Nouthetic counseling",
"Nude psychotherapy",
"Object relations theory",
"Obsessive%E2%80%93compulsive disorder",
"Obsessive%E2%80%93compulsive personality disorder",
"Obsessive-compulsive disorder",
"Obsessive-compulsive personality disorder",
"Occupational health psychology",
"Occupational therapy in the management of seasonal affective disorder",
"Ondine%27s curse",
"Oneirophrenia",
"Onychotillomania",
"Opioid",
"Opioid dependence",
"Oppositional defiant disorder",
"Organic mental disorders",
"Orthodox psychotherapy",
"Orthorexia",
"Other specified feeding or eating disorder",
"Outline of psychology",
"Outline of the psychiatric survivors movement",
"Pain disorder",
"Pain management",
"Palliative medicine",
"Panic disorder",
"Paranoid personality disorder",
"Paraphilia",
"Parasomnia",
"Parent%E2%80%93child interaction therapy",
"Parent management training",
"Parkinson%27s Disease",
"Parkinson%27s disease",
"Partialism",
"Pastoral counseling",
"Pathological gambling",
"Penetrating head injury",
"Persecutory delusion",
"Person-centered therapy",
"Personality disorder",
"Personality psychology",
"Pervasive developmental disorder",
"Pervasive developmental disorder not otherwise specified",
"Phencyclidine",
"Philadelphia Association",
"Philosophy of psychiatry",
"Phobia",
"Phobic disorder",
"Phonological disorder",
"Physical abuse",
"Physical dependence",
"Pica (disorder)",
"Pick%27s disease",
"Play therapy",
"Poetry therapy",
"Political abuse of psychiatry",
"Political abuse of psychiatry in the Soviet Union",
"Political psychology",
"Poly drug use",
"Positive psychology",
"Positive psychotherapy",
"Postpartum depression",
"Postpartum psychosis",
"Posttraumatic stress disorder",
"Postural Integration",
"Pragmatic language impairment",
"Premature ejaculation",
"Primal Integration",
"Primal therapy",
"Primary age-related tauopathy",
"Primary hypersomnia",
"Primary insomnia",
"Primary polydipsia",
"Problem gambling",
"Process oriented psychology",
"Process psychology",
"Progressive counting (PC)",
"Prolonged exposure therapy",
"Provocative therapy",
"Pseudologia fantastica",
"Psychedelic therapy",
"Psychiatric diagnosis",
"Psychiatric disorders of childbirth",
"Psychiatric epidemiology",
"Psychiatric genetics",
"Psychiatric survivors movement",
"Psychiatrist",
"Psychiatry",
"Psycho-oncology",
"Psychoanalysis",
"Psychodrama",
"Psychodynamic psychotherapy",
"Psychogenic amnesia",
"Psychogenic pain",
"Psychology",
"Psychology of religion",
"Psychopharmacology",
"Psychosis",
"Psychosomatic medicine",
"Psychosurgery",
"Psychosynthesis",
"Psychotherapy",
"Psychotic disorder",
"Pulsing (bodywork)",
"Pyromania",
"Quantitative psychology",
"REM Sleep Behavior Disorder Screening Questionnaire",
"REM Sleep Behavior Disorder Single-Question Screen",
"Rapid eye movement sleep behavior disorder",
"Rational emotive behavior therapy",
"Rational living therapy",
"Reactive attachment disorder",
"Reality therapy",
"Rebirthing-breathwork",
"Rebound effect",
"Recovered-memory therapy",
"Recurrent brief depression",
"Reichian therapy",
"Relational-cultural therapy",
"Relational disorder",
"Relationship counseling",
"Relationship obsessive%E2%80%93compulsive disorder",
"Remote therapy",
"Residual schizophrenia",
"Restless legs syndrome",
"Retarded depression",
"Retrograde amnesia",
"Rett syndrome",
"Rosenhan experiment",
"Royal Australian and New Zealand College of Psychiatrists",
"Royal College of Psychiatrists",
"Rumination (psychology)",
"Rumination syndrome",
"Sandplay therapy",
"Schema therapy",
"Schizoaffective disorder",
"Schizoid personality disorder",
"Schizophrenia",
"Schizophreniform disorder",
"Schizotypal personality disorder",
"School psychology",
"Scopophobia",
"Seasonal affective disorder",
"Sedative",
"Selective mutism",
"Self-defeating personality disorder",
"Self-enucleation",
"Self-harm",
"Sensorimotor psychotherapy",
"Separation anxiety disorder",
"Sex therapy",
"Sexual anhedonia",
"Sexual dysfunction",
"Sexual fetishism",
"Sexual identity therapy",
"Sexual masochism disorder",
"Sexual maturation disorder",
"Sexual relationship disorder",
"Sexual sadism disorder",
"Shared psychotic disorder",
"Sleep disorder",
"Sleep medicine",
"Sleep paralysis",
"Sleep sex",
"Sleep terror disorder",
"Sleepwalking disorder",
"Social anxiety disorder",
"Social phobia",
"Social psychology",
"Social therapy",
"Solution focused brief therapy",
"Somatic experiencing",
"Somatic psychology",
"Somatic symptom disorder",
"Somatization disorder",
"Somatoform disorder",
"Specific phobia",
"Sport psychology",
"Status dynamic psychotherapy",
"Stereotypic movement disorder",
"Stockholm syndrome",
"Structural family therapy",
"Stuttering",
"Subfields of psychology",
"Substance-related disorder",
"Supportive psychotherapy",
"Systematic desensitization",
"Systemic therapy",
"T-groups",
"Taiwanese Society of Child and Adolescent Psychiatry",
"Tardive dyskinesia",
"Therapeutic community",
"Thought Field Therapy",
"Tic disorder",
"Timeline of psychology",
"Tourettes Syndrome",
"Traffic psychology",
"Transactional analysis",
"Transference focused psychotherapy",
"Transient global amnesia",
"Transpersonal psychology",
"Transtheoretical model",
"Transvestic disorder",
"Trichotillomania",
"Twelve-step program",
"Vegetotherapy",
"Wilderness therapy",
"Working Commission to Investigate the Use of Psychiatry for Political Purposes",
"World Psychiatric Association",
"Writing therapy",
"Outline of the psychiatric survivors movement",
"Badminton",
"Badminton World Federation",
"Shuttlecock",
"Racket (sports equipment)",
"Net (device)",
"BWF World Ranking",
"Presidencies and provinces of British India",
"Badminton House",
"Badminton England",
"Badminton Europe",
"Badminton Asia",
"Badminton Pan Am",
"Badminton Confederation of Africa",
"Badminton Oceania",
"BWF World Championships",
"BWF World Tour",
"All England Open Badminton Championships",
"BWF Super Series",
"Scoring system development of badminton",
"Ball badminton",
"Speed badminton",
"Hanetsuki",
"Battledore and shuttlecock",
"Carbon fiber reinforced polymer",
"Tennis",
"Jianzi",
"Grip (badminton)",
"Yonex",
"BadmintonScotland",
"Stringing machine",
"Squash (sport)",
"Table tennis",
"Referee",
"Racquetball",
"Li-Ning",
"World Badminton Federation",
"BWF Super Series Finals",
"Badminton at the Summer Olympics",
"1992 Summer Olympics",
"1972 Summer Olympics",
"Badminton at the 1972 Summer Olympics",
"Badminton at the 1988 Summer Olympics",
"Badminton at the 1992 Summer Olympics",
"Badminton at the 1996 Summer Olympics",
"Badminton at the 2000 Summer Olympics",
"Badminton at the 2004 Summer Olympics",
"Badminton at the 2008 Summer Olympics",
"Badminton at the 2012 Summer Olympics",
"Badminton at the 2016 Summer Olympics",
"Badminton at the 2020 Summer Olympics",
"BWF Para-Badminton World Championships",
"Thomas Cup",
"Uber Cup",
"Sudirman Cup",
"African Badminton Championships",
"Badminton Confederation of Africa",
"Badminton Asia Championships",
"Badminton Asia Junior Championships",
"European Badminton Championships",
"European Junior Badminton Championships",
"Oceania Badminton Championships",
"Pan Am Badminton Championships",
"Pan Am Junior Badminton Championships",
"Commonwealth Games",
"Badminton World Cup",
"World Badminton Grand Prix Finals",
"BWF World Ranking",
"BWF World Junior Ranking",
"Badminton Hall of Fame",
"India national badminton team",
"Asian Games",
"Badminton Association of India",
"Indian National Badminton Championships",
"Badminton in India",
"Premier Badminton League",
"2016 Premier Badminton League",
"Delhi Dashers",
"Hyderabad HotShots",
"Awadhe Warriors",
"Delhi Smashers",
"Pune Pistons",
"Mumbai Masters",
"Bengaluru Raptors",
"Mumbai Rockets",
"Ahmedabad Smash Masters",
"Chennai Smashers",
"Hyderabad Hunters",
"Northeastern Warriors",
"Son Wan-ho",
"Lin Dan",
"Lee Chong Wei",
"Saina Nehwal",
"P. V. Sindhu",
"Taufik Hidayat",
"Parupalli Kashyap",
"Jan %C3%98. J%C3%B8rgensen",
"Viktor Axelsen",
"Mumbai Rockets",
"BWF Grand Prix Gold and Grand Prix",
"BWF International Challenge",
"BWF International Series",
"BWF Future Series",
"Talk%3ABadminton",
"Portal:Badminton",
"Wikipedia:WikiProject Badminton",
"Dance",
"History of dance",
"List of national dances",
"List of ethnic, regional, and folk dances by origin",
"List of dance occupations",
"Choreography",
"Outline of dance",
"Dance move",
"Dance technology",
"List of dance companies",
"List of dancers",
"Group dance",
"Dance and health",
"Dancing mania",
"Modern dance",
"Dance education",
"Dance in mythology and religion",
"Dance therapy",
"Dance music",
"List of dance style categories",
"List of folk dances sorted by origin",
"List of novelty/fad dances",
"Acharuli",
"Acro dance",
"Affranchi",
"Allemande",
"An Dro",
"Angama",
"Argentine Tango",
"Arkan",
"Assyrian folk dance",
"Assyrian",
"Attan",
"Azonto",
"Bachata",
"Baagh Naach",
"Bagurumba",
"Balboa",
"Ballet",
"Ballos",
"Ballroom dance",
"Ballu tundu",
"Bandari dance",
"Bardo Chham",
"Barn dance",
"Baroque dance",
"Barynya",
"Basse danse",
"Renaissance dances",
"Basque dance",
"BBoying",
"Belly dance",
"Beguine",
"Bergamask",
"Bhangra",
"Bharatanatyam",
"Big Apple",
"Bihu dance",
"Biyelgee",
"Black Bottom",
"Lindy Hop",
"Blues",
"Bolero",
"Bollywood",
"Bomba",
"Bon Odori",
"Boogaloo",
"Boogie-woogie",
"Bop music",
"Bossa nova",
"Borrowdale",
"Boston",
"Bourrée",
"Branle",
"Breakaway",
"Breakdancing",
"Bugg",
"Bump and grind",
"Bunny Hop",
"Butoh",
"Butterfly dance",
"Buyō",
"Candle dance",
"Cat Daddy",
"Cajun dance",
"Cakewalk",
"Calypso",
"Candombe",
"Canaries dance",
"Can-can",
"Capoeira",
"Caporales",
"Carabinier",
"Cariñosa",
"Carioca",
"Carol",
"Castle Walk",
"Căluş",
"Ceroc",
"Chaabi",
"Chacarera",
"Chaconne",
"Cha cha cha",
"Chamame",
"Charleston",
"Chasapiko",
"Cheerleading",
"Chicken Dance",
"Chicken Noodle Soup",
"Chhau dance",
"Chula",
"Chumba",
"Cinquepace",
"Circassian Dance",
"Circle dance",
"Cirebon mask dance",
"Clog dance",
"Clogging",
"Clowning",
"Cocek",
"Collegiate shag",
"Compas",
"Condong",
"Conga",
"Contact improvisation",
"Contemporary dance",
"Contra dance",
"Cordax",
"Cossack dance",
"Cotillion",
"Country/western dance",
"Country dance",
"Country/Western Two-step",
"Courante",
"Court dance",
"Crip walk",
"Csárdás",
"Cuarteto",
"Cueca",
"Cumbia",
"Cumbia Villera",
"Cupid Shuffle",
"Dabke",
"Dalkhai",
"Dancer's Delight",
"Dances of Universal Peace",
"Danda nata",
"Dancehall",
"Dandia",
"Danza de tijeras",
"Dhalo",
"Dhamail",
"Diablada",
"Dilan",
"Disco",
"Dappan koothu",
"Doublebugg",
"Dougie",
"Dragon dance",
"Duranguense",
"Dutty Wine",
"East Coast Swing",
"Eisa",
"Electro dance",
"Electric Slide",
"English Country Dance",
"Ethnic dance",
"Erotic",
"Fan dance",
"Fandango",
"Farandole",
"Faroese dance",
"Farruca",
"Flamenco",
"Floss",
"Folk dance",
"Formation dance",
"Forró",
"Foxtrot",
"Freak dancing",
"The Freddy",
"Frevo",
"Frug",
"Freestyle",
"Galliard",
"Galop",
"Garba",
"Gankino",
"Gangnam Style",
"Gavotte",
"Gaudiya Nritya",
"Gigue",
"Ghoomar",
"Ghumura Dance",
"Giddha",
"Gombey",
"Gotipua",
"Grizzly Bear",
"Grinding",
"Guaguancó",
"Guapacha",
"Gumboot dance",
"Hakken",
"Halay",
"Hambo",
"Hand jive",
"Hardcore Dancing",
"Harlem Shake",
"Hasapiko",
"Headbanging",
"Highland dancing",
"Hip hop dance",
"Historical dance",
"Hitch hike",
"Hokey Pokey",
"Hootchy-Kootchy",
"Humppa",
"Hopak",
"House dance",
"Hora",
"Horon",
"Hornpipe",
"Huayno",
"Hula",
"Hully Gully",
"Hustle",
"Ice dancing",
"Ikariotikos",
"Improv Tribal Style Belly Dance",
"Intercessory dance",
"International folk dance",
"Interpretive dance",
"Irish Dance",
"Irish Sean-Nós Dance",
"Irish Stepdance",
"Israeli folk dancing",
"Japanese traditional dance",
"Jarabe tapatío",
"Jazz dance",
"Jenkka",
"Jerkin'",
"Jig",
"Jitterbug",
"Jitterbug Stroll",
"Jive",
"Joged",
"John Wall dance",
"Jota",
"Jove Malaj Mome",
"Jumpstyle",
"Kachāshī",
"Kalamatianos",
"Kalymnikos",
"Kamarinskaya",
"Karsilama",
"Karşılama",
"Kathak",
"Kathakali",
"Kazachok",
"Keisabadi",
"Kerala Natanam",
"Khasapiko",
"Khattak Dance",
"Khigga",
"Khon",
"Khorovod",
"Kizomba",
"Kleistos",
"Klezmer",
"Klompendansen",
"Koftos",
"Kolbasti",
"Kolo",
"Kolomyjka",
"Kontradans",
"Kopanitsa",
"Kotsari",
"Kozachok",
"Krakowiak",
"Krishnanattam",
"Krumping",
"Kuchipudi",
"Kurdish dance",
"Kujawiak",
"Kumina",
"La Cucaracha",
"Lambada",
"Lambeth Walk",
"Landler",
"Lap dance",
"Latin dance",
"Lavani",
"Lavolta",
"Ländler",
"Legong",
"Lerikos",
"LeRoc",
"Letkajenkka",
"Leventikos",
"Lezginka",
"Limbo",
"Lindy Hop",
"Line dance",
"Lion dance",
"Liscio",
"Locking",
"Long Sword",
"Loure",
"Lurish dance",
"Lyrical dance",
"Macarena",
"Madison",
"Maglalatik",
"Malaguena",
"Mambo",
"Manipuri",
"Mapale",
"Marimba",
"Marinera",
"Mashed Potato",
"Matachin",
"Maypole dance",
"Maxixe",
"Mazur",
"Mazurka",
"Medieval dance",
"Melbourne Shuffle",
"Merengue",
"Méringue",
"Metelytsia",
"Milonga",
"Minuet",
"Morenada",
"Modern dance",
"Modern Jive",
"Mohiniyattam",
"Molly dance",
"Moonwalker",
"Morris dance",
"Moshing",
"Muiñeira",
"Novelty and fad dances",
"The Nutbush",
"Nacnī",
"Oberek",
"Odissi",
"Ojapali",
"Pachanga",
"Pagode",
"Pakurumo",
"Palo de Mayo",
"Panthi",
"Pantomime",
"Pantsula",
"Para Para",
"Parasol dance",
"Participation dance",
"Partner dance",
"Passacaglia",
"Passepied",
"Pasillo",
"Pasodoble",
"Pavane",
"Peabody",
"Peewee style",
"Pentozalis",
"Persian dance",
"Pidikhtos",
"Pogo",
"Pole dancing",
"Polka",
"Polka-mazurka",
"Polonaise",
"Pols",
"Polska",
"Pom Squad",
"Pony",
"Popping",
"Pop, Lock, and Drop It",
"Prophetic dance",
"Pryvit",
"Punta",
"Pyrrhichios",
"Quadrille",
"Quickstep",
"Quebradita",
"Raas",
"Rain dancing",
"Ramvong",
"Rapper sword",
"Raut Nacha",
"Raqs Sharqi",
"Rebetiko dances",
"Red River Jig",
"Redowa",
"Reel",
"Regency dance",
"Reggaeton",
"Renaissance dance",
"Rhumba",
"Rigaudon",
"Robot dance",
"Rock and Roll",
"Round dance",
"Rumba",
"Salsa",
"Salsa Rueda",
"Samba dance",
"Samba de Gafieira",
"Samba",
"Sarabande",
"Sardana",
"Sattriya dance",
"Schottische",
"Scottish country dance",
"Scottish highland dance",
"Sean-Nós Dance",
"Seguidilla",
"Sequence dance",
"Serra",
"Set Dance",
"Sevillana",
"Carolina Shag",
"Collegiate Shag",
"St. Louis Shag",
"Shake",
"Shim Sham",
"Shimmy",
"Shuffle",
"Single Swing",
"Sirtaki",
"Skank",
"Skip jive",
"Slängpolska",
"Slip jig",
"Slow dance",
"Slow Foxtrot",
"Social dance",
"Son",
"Sousta",
"Square dance",
"Traditional square dance",
"Modern Western square dance",
"Stage diving",
"Stanky Legg",
"Step dance",
"Stiletto dance",
"Street dance",
"The Strictly",
"Swing",
"Suzie Q",
"Syrtos",
"Kalamatianos Syrtos",
"Tambourin",
"Tandav",
"Tango",
"Thirayattam",
"Tanoura",
"Tap dance",
"Tarantella",
"Tau'olunga",
"Tecktonik",
"Temani",
"Texas Tommy",
"The Thistle",
"Tinikling",
"Time Warp",
"Tinku",
"Tondero",
"Tourdion",
"Traditional dance",
"Tranky Doo",
"Trata",
"Trepak",
"Tribal Style Belly Dance",
"Troika",
"Tsakonikos",
"Tsamiko",
"Tsifteteli",
"Tumba",
"Tutting",
"Twerking",
"Twist",
"Two-step",
"Twoubadou",
"Universal Peace",
"Ukrainian dance",
"Urban Dance",
"Vals",
"Valse à deux temps",
"Verbunkos",
"Vintage dance",
"Virginia reel",
"Vogue",
"Volte",
"Waacking",
"Waltz",
"Boston",
"Walking Boston",
"Cross-step waltz",
"Hesitation Waltz",
"Slow waltz",
"Viennese Waltz",
"Valse à deux temps",
"Watusi",
"West Coast Swing",
"Western swing",
"Sophisticated Swing",
"Western promenade dance",
"Whip",
"Whirling",
"Winterguard",
"Wolosso",
"Worship dance",
"Xibelani",
"Yablochko",
"Yakshagana",
"YMCA",
"Yosakoi",
"Yowla",
"Zamacueca",
"Zamba",
"Zapateado",
"Zapin",
"Zeibeks",
"Zonaradiko",
"Zouk",
"Zumba",
"Zwiefacher",
"Zydeco",
"Competitive dance"}